homeowners_website/building_service/urls.py
from django.urls import path
from . import views

app_name = 'building_service'

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/profile/add_account/', views.add_account, name='add_account'),
    path('accounts/profile/add_readings/<str:account_number>/', views.add_readings, name='add_readings'),
    path('accounts/profile/get_bill/<str:account_number>/', views.get_bill, name='get_bill'),
    path('accounts/profile/readings_history/<str:account_number>/', views.readings_history, name='readings_history')
]

homeowners_website/homeowners_website/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('building_service.urls', namespace='building_service')),
    path('admin/', admin.site.urls),
    # Подключаем urls.py приложения для работы с пользователями.
    path('auth/registration/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls'))
    
] 

homeowners_website/users/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import SignUpView
from . import views

app_name = 'users'

urlpatterns = [
    path('', SignUpView.as_view(), name='registration')
]

homeowners_website/building_service/models.py
from django.db import models
from users.models import PersonalAccount # Предполагается, что модель Account находится в приложении users

class Utilities(models.Model):
  name = models.CharField(max_length=255, verbose_name="Название")
  tariff = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, verbose_name="Тариф")
  units = models.CharField(max_length=10, blank=True, null=True, verbose_name='Единицы измерения')
  norm = models.DecimalField(max_digits=10, decimal_places=3, null=True, blank=True, verbose_name="Норматив")

  def __str__(self):
    return self.name
  
  class Meta:
      verbose_name = "Коммунальная услуга"
      verbose_name_plural = "Коммунальные услуги"


class Meters(models.Model):
  individual_number = models.CharField(max_length=50, unique=True, verbose_name="Индивидуальный номер")
  account = models.ForeignKey(PersonalAccount, on_delete=models.CASCADE, related_name='meters', verbose_name="Лицевой счет")
  utility = models.ForeignKey(Utilities, on_delete=models.CASCADE, related_name='meters', verbose_name="Услуга")

  def __str__(self):
    return f"Счетчик №{self.individual_number} (Лицевой счет: {self.account_id}, Услуга: {self.utility.name})"

  class Meta:
      verbose_name = "Счётчик"
      verbose_name_plural = "Счётчики"


class MeterReadings(models.Model):
  meter = models.ForeignKey(Meters, on_delete=models.SET_NULL, related_name='readings', verbose_name="Счетчик", null=True)
  month = models.DateField(verbose_name="Месяц показания")
  reading = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Показание")

  def __str__(self):
    return f"Показания счетчика {self.meter.utility} №{self.meter.individual_number} ({self.meter.account}) за {self.month.strftime('%Y-%m')}: {self.reading}"

  class Meta:
      verbose_name = "Показание счётчика"
      verbose_name_plural = "Показания счётчиков"


class PaymentRecords(models.Model):
  account = models.ForeignKey(PersonalAccount, on_delete=models.SET_NULL, related_name='payments', verbose_name="Лицевой счет", null=True)
  utility = models.ForeignKey(Utilities, on_delete=models.CASCADE, related_name='payments', verbose_name="Услуга")
  amount_paid = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Оплачено (руб.)")
  payment_date = models.DateField(verbose_name="Месяц оплаты")

  def __str__(self):
    return f"Оплата {self.amount_paid} руб. за {self.payment_date.strftime('%Y-%m')} (Лицевой счет: {self.account_id}, Услуга: {self.utility.name})"
  
  class Meta:
      verbose_name = "Запись об оплате"
      verbose_name_plural = "Записи об оплате"

homeowners_website/building_service/forms.py
import datetime
from django import forms


class AddNewAccountForm(forms.Form):
    account_number = forms.CharField(label='Номер лицевого счета', max_length=6, help_text='Первые две цифры тип объекта - «01» квартиры, офисы; «02» гараж и т.д. Далее три цифры - это номер квартиры, последняя цифра отвечает за разделение лицевых счетов (0 не разделён, или порядковый номер разделения). Например, для квартиры №1 он будет 010010, для квартиры №10 он будет 010100')
    previous_payment = forms.DecimalField(label='Введите сумму последнего платежа с точностью до копеек, внесенного по услуге "Электроснабжение"')

class AddReadingsForm(forms.Form):
    # period = forms.ChoiceField(choices=[
    #     ('current', 'Текущий период'),
    #     ('previous', 'Предыдущий период'),
    # ], label='Выберите период')
    cold_water_reading = forms.DecimalField(label='Введите текущее показание')
    hot_water_reading = forms.DecimalField(label='Введите текущее показание')
    electricity_reading = forms.DecimalField(label='Введите текущее показание')


def validate_year(value):
    current_year = datetime.datetime.now().year
    if not 2016 <= value <= current_year: # Пример диапазона, измените по необходимости
        raise forms.ValidationError('Год должен быть в диапазоне от 2016 до %(current_year)s', params={'current_year': current_year})


class ChooseMonthForm(forms.Form):
    month = forms.IntegerField(min_value=1, max_value=12, label='Введите номер месяца')
    year = forms.IntegerField(label='Введите год', validators=[validate_year])

homeowners_website/building_service/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from users.models import PersonalAccount, MyUser
from django.contrib.auth import get_user_model
from .forms import AddNewAccountForm, AddReadingsForm, ChooseMonthForm
from .models import MeterReadings, Meters, PaymentRecords, Utilities
from django.core.exceptions import PermissionDenied
from django.db.models import Max
from datetime import date, datetime
from django.urls import reverse
from django.contrib import messages
from .utils import count_meter_dependent_payment
import math

    

def index(request):
    template = 'index.html'
    return render(request, template)

def get_latest_payment_amount(account_number):
    """
    Возвращает сумму самого недавнего платежа для заданного номера лицевого счета.
    Возвращает None, если платежей нет.
    """
    try:
        electricity_utility = Utilities.objects.get(name='Электроснабжение')  
        latest_payment = PaymentRecords.objects.filter(
            account__account_number=account_number,
            utility=electricity_utility
        ).order_by('-payment_date').first()

        if latest_payment:
            return latest_payment.amount_paid
        else:
            return None

    except PersonalAccount.DoesNotExist:
        return None


@login_required
def profile(request):
    template = 'building_service/profile.html'
    user = request.user
    accounts = user.accounts.all().order_by('account_number')
    # account = PersonalAccount.objects.get(id=1)
    # user.accounts.remove(account)
    months = {
            1: "января", 2: "февраля", 3: "марта", 4: "апреля", 5: "мая",
            6: "июня", 7: "июля", 8: "августа", 9: "сентября", 10: "октября",
            11: "ноября", 12: "декабря"
        }
    date_now = date.today()
    next_month_10th = date(date_now.year + (date_now.month == 12), (date_now.month % 12) + 1, 10)
    diff = next_month_10th - date_now
    context = {'user': user,
               'accounts': accounts,
               'month': date_now.strftime('%m.%Y'),
               'month_text': months[(date_now.month + 1) % 12 or 12],
               'diff': diff.days
               }    
    # try:
    # # Retrieve the account with a specific id (e.g., id=1)
    #     account = PersonalAccount.objects.get(id=1)
    # # Get the users associated with the account
        
    # except PersonalAccount.DoesNotExist:
    #     print("PersonalAccount with id=1 not found.")

    # try:
    # # Retrieve the account with a specific id (e.g., id=1)
    #     user = MyUser.objects.get(id=1)
    #     user2 = MyUser.objects.get(id=3)
    #     user.accounts.add(account)
    #     user2.accounts.add(account)
    #     user.accounts.remove(account)
    #     user2.accounts.remove(account)
    # # Get the users associated with the account
    #     accounts = user.accounts.all()
    # except MyUser.DoesNotExist:
    #     print("User with id=1 not found.")

    # related_users = account.users.all()
    # # Полученный из БД QuerySet передаём в словарь контекста:
    # context = {
    #     'ice_cream_list': related_users,
    #     'accounts': accounts
    # }
    return render(request, template, context)

@login_required
def add_account(request):
    template = 'building_service/add_account_form.html'
    user = request.user
    if request.POST:
        form = AddNewAccountForm(request.POST)
        if form.is_valid():
            account_number = form.cleaned_data['account_number']
            try:
                account = PersonalAccount.objects.get(account_number=account_number)
                if account in user.accounts.all():
                    message = 'Лицевой счёт с таким номером уже добавлен.'
                else:
                    latest_payment = get_latest_payment_amount(account_number)  
                    if latest_payment == form.cleaned_data['previous_payment']:
                        user.accounts.add(account)
                        message = 'Лицевой счет добавлен.' 
                    else:
                        message = 'Данные о платеже не совпали.'            
            except PersonalAccount.DoesNotExist:
                message = 'Лицевого счета с таким номером не существует.'
        else:
            message = 'Неправильно заполнена форма!'    
            
    else:
        form = AddNewAccountForm()
        message = ''

    context = {'user': user,
                'form': form,
                'message': message}  
      
    return render(request, template, context)




@login_required
def add_readings(request, account_number):
    
    template = 'building_service/bill_form.html'
    user = request.user
    

    try:
        
        account = PersonalAccount.objects.get(account_number=account_number)
        if account in user.accounts.all():
            address = f'г. Москва, ул. Новогодняя, д.23, к.{account.building}, кв.{account.apartment_number}'
            #
            utilities_names = ["ХВС", "ГВС", "Электроснабжение"]
            meter_data = {}

            for utility_name in utilities_names:
                try:
                    utility = Utilities.objects.get(name=utility_name)
                    meter = Meters.objects.get(account=account, utility=utility)
                    last_reading = MeterReadings.objects.filter(meter=meter).aggregate(Max('month'))
                    last_month = last_reading['month__max']
                    if last_month:
                        last_reading_value = MeterReadings.objects.get(meter=meter, month=last_month).reading
                    else:
                        last_reading_value = 0

                    meter_data[utility_name] = {
                        "individual_number": meter.individual_number,
                        "last_reading": last_reading_value,
                        "last_month": last_month,
                        "id": meter.id
                    }
                except (Utilities.DoesNotExist, Meters.DoesNotExist, MeterReadings.DoesNotExist):
                    meter_data[utility_name] = {
                        "individual_number": None,
                        "last_reading": 0,
                        "last_month": None
                    }

            initial_data = {
                'cold_water_reading': meter_data['ХВС']['last_reading'],
                'hot_water_reading': meter_data['ГВС']['last_reading'],
                'electricity_reading': meter_data['Электроснабжение']['last_reading']
            }

            if request.POST:
                form = AddReadingsForm(request.POST)
                try:
                    if form.is_valid():
                        cold_water_reading = form.cleaned_data['cold_water_reading']
                        hot_water_reading = form.cleaned_data['hot_water_reading']
                        electricity_reading = form.cleaned_data['electricity_reading']
                        if cold_water_reading >= initial_data['cold_water_reading'] and hot_water_reading >= initial_data['hot_water_reading'] and electricity_reading >= initial_data['electricity_reading']:
                            today = date.today()
                            if today.day in range(1, 11):
                                month = today.month - 1
                            else:
                                month = today.month
                            
                            
                           # get_readings = {}
                            try:
                                if not meter_data['ХВС']['last_month']: 
                                    raise ValueError
                                else:
                                    last_month_cold_water = meter_data['ХВС']['last_month'].month
                                    if month == last_month_cold_water:
                                        meter = Meters.objects.get(id=meter_data['ХВС']['id'])
                                        reading_object = MeterReadings.objects.filter(meter=meter).order_by('-month').first()
                                        reading_object.reading = cold_water_reading
                                        reading_object.save(update_fields=['reading']) 
                                    else:
                                        raise ValueError
                                        #get_readings['ХВС'] = reading_object
                            except ValueError:
                                meter = Meters.objects.get(id=meter_data['ХВС']['id'])
                                date_new = today.replace(month=month)
                                MeterReadings.objects.create(
                                meter=meter,
                                month=date_new, 
                                reading=cold_water_reading
                            )
                                #get_readings['ХВС'] = new_reading
                            try:
                                if not meter_data['ГВС']['last_month']:
                                    raise ValueError
                                else:
                                    last_month_hot_water = meter_data['ГВС']['last_month'].month    
                                    if month == last_month_hot_water:
                                        meter = Meters.objects.get(id=meter_data['ГВС']['id'])
                                        reading_object = MeterReadings.objects.filter(meter=meter).order_by('-month').first()
                                        reading_object.reading = hot_water_reading
                                        reading_object.save(update_fields=['reading']) 
                                        #get_readings['ГВС'] = reading_object
                                    else:
                                        raise ValueError
                            except ValueError:

homeowners_website/templates/building_service/add_account_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
{% if message %}
    <b>{{ message }}</b>
    {% endif %}
  <div class="card">
    
    <div class="card-header">
      Добавить лицевой счет
    </div>
    
    <div class="card-body">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Отправить" %}
  </form>

  
</div>
</div>
</div>  
{% endblock %}   

homeowners_website/templates/building_service/bill_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <b><li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li></b>
        {% endfor %}
    </ul>
{% endif %}

{% if message %}
<p>{{ message }}</p>
{% endif %}
<div class="card col-7 m-1">
    <div class="card-header">
        Подать показания счётчиков
    </div>
    <div class="card-body">
        <form method="post">
            <p>Пожалуйста, проверьте, что адрес правильный:
            <b>{{ address }}</b></p>
            {% csrf_token %}
            {% comment %} <span>Выберите период </span>
                {{ form.period }} <br> <br> {% endcomment %}
            <p>Введите данные счётчиков</p>
            
            <ul >
                
                <li><b>ХВС</b><br>
                    Счётчик № {{ meter_data.ХВС.individual_number }} <br>
                    Предыдущее показание: {{ meter_data.ХВС.last_reading }} <br>
                    Текущее показание:
                    {{ form.cold_water_reading }}   
                    {% comment %} {{ meter_data.ХВС.id }} {% endcomment %}
                </li> 
                <li><b>ГВС</b><br>
                    Счётчик № {{ meter_data.ГВС.individual_number }} <br>
                    Предыдущее показание: {{ meter_data.ГВС.last_reading }} <br>
                    Текущее показание:
                    {{ form.hot_water_reading }}   
                </li> 
                <li><b>Электроснабжение</b><br>
                    Счётчик № {{ meter_data.Электроснабжение.individual_number }} <br>
                    Предыдущее показание: {{ meter_data.Электроснабжение.last_reading }} <br>
                    Текущее показание:
                    {{ form.electricity_reading }}   
                </li> 
            </ul> 
               
            {% bootstrap_button button_type="submit" content="Отправить показания" %}
        </form>
    </div>
</div> 
{% endblock %}   

homeowners_website/templates/building_service/bill_form_new.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
{% if message %}
<p>{{ message }}</p>
{% endif %}
<div class="card m-1">
    <div class="card-header">
        Квитанция на оплату за {{ date }}
    </div>
    <div class="card-body" style="overflow-x: auto;">
        <p>Адрес:
        <b>{{ address }}</b></p>
        <table class="table table-striped" style="font-size: 0.8em;">  <!-- Bootstrap classes for styling -->
            <thead>
              <tr>
                <th></th>
                <th>Тариф</th>
                <th>Новое показание</th>
                <th>Предыдущее показание</th>
                <th>Норматив</th>
                <th>Площадь</th>
                <th>Кол-во проживающих</th>
                <th>Объем потребленных услуг</th>
                <th>Сумма (₽)</th>
                {% comment %} <th>Площадь</th>
                <th>ХВС (₽/м³)</th>
                <th>ГВС (₽/м³)</th>
                <th>Электроснабжение (₽/кВт ч)</th>
                <th>Отопление</th>
                <th>Водоотведение</th>
                <th>Взнос на капремонт</th>
                <th>Сод. жилья</th>
                <th>Обращение с ТКО</th> {% endcomment %}
              </tr>
            </thead>
            <tbody>
                
                
                    {% for key, item in payment_results.items %}
                    <tr>
                    <td><b>
                        {{ key }}
                    </b>
                    </td>
                    <td>
                        {% if item.tariff %}
                        {{ item.tariff }} {{ item.units }}
                        {% else %}
                        -
                        {% endif %}
                        
                    </td>
                    <td>
                        {% if item.new_reading %}
                        {{ item.new_reading }}
                        {% else %}
                        -
                        {% endif %}
                        
                    </td>
                    <td>
                        {% if item.previous_reading %}
                        {{ item.previous_reading }}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        {% if item.norm %}
                        {{ item.norm }}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        {{ item.area }}
                    </td>
                    <td>
                        {{ item.number_of_people }}
                    </td>
                    <td>
                        {% if item.difference %}
                        {{ item.difference|floatformat:2 }}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        {{ item.result|floatformat:2 }}
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <td><b>Итого</b></td><td>{{ total_sum }} руб.</td>
                </tr>
            </tbody>

          </table>
          <p>Вы можете оплатить услуги в любом удобном банке, указав реквизиты ТСЖ и сумму.</p>

    </div>
</div> 
{% endblock %}   

homeowners_website/templates/building_service/error.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    <p>{{ message }}</p>
{% endblock %}  

homeowners_website/templates/building_service/profile.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
{% if user.is_authenticated %}
<div class="alert alert-primary my-0 py-2">
  Срок оплаты ЖКУ за текущий месяц - до 10 числа следующего месяца. <br>
  Дней до 10 {{ month_text }}: {{ diff }}
  </div>
<div class=" my-1">
      
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Пользователь: <b>{{ user.username }}</b> <br>
            
          Email: <b>{{ user.email }}</b>
          
            
        </li>
          <li class="list-group-item"><b>Лицевые счета:</b></li>
        {% if user.accounts.all %}
          {% for account in accounts %}
            <li class="list-group-item">{{ account }}
              
                <div class="d-flex flex-wrap">
              <a href="{% url 'building_service:add_readings' account.account_number %}" class="my-2 mx-2 btn btn-primary btn-sm">Подать показания счётчиков</a>
              <a href="{% url 'building_service:get_bill' account.account_number %}" class="my-2 mx-2 btn btn-primary btn-sm">Получить квитанцию</a>
              <a href="{% url 'building_service:readings_history' account.account_number %}" class="my-2 mx-2 btn btn-primary btn-sm">История показаний</a>
            </div>
              
            </li>
          {% endfor %}
        {% else %}
        <li class="list-group-item">Лицевые счета не привязаны.</li>
        {% endif %}
        
        <li class="list-group-item"><a href="{% url 'building_service:add_account' %}" class="my-2 ">Добавить лицевой счёт</a></li>
        </ul>
{% endif %}

{% endblock %}

homeowners_website/templates/building_service/readings_history.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<div class="card col-10 m-1">
    <div class="card-header">
        История показаний
    </div>
    <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">{{ account }}</li>
            <li class="list-group-item"><form >
    
                {% bootstrap_form form  %}
                {% bootstrap_button button_type="submit" content="Показать" %}
                
                </form>
            
            
{% if result_dict %}
    <table class="table table-striped my-3" >  <!-- Bootstrap classes for styling -->
        <thead>
          <tr>
            <th></th>
            <th>Номер счётчика</th>
            <th>Объем услуг</th>
            <th>Текущее показание</th>
            <th>Предыдущее показание</th>
            <th>Единицы измерения</th>
            
          </tr>
        </thead>
        <tbody>
                {% for key, item in result_dict.items %}
                <tr>
                <td><b>
                    {{ key }}
                </b>
                </td>
                <td>
                    {% if item %}
                    {{ item.number }}
                    {% else %}
                    -
                    {% endif %}
                </td>
                <td>
                    {% if item %}
                    {{ item.difference }}
                    {% else %}
                    -
                    {% endif %}
                    
                </td>
                <td>
                    {% if item %}
                    {{ item.reading_cur }}
                    {% else %}
                    -
                    {% endif %}
                </td>
                <td>
                    {% if item and item.reading_prev %}
                    {{ item.reading_prev }}
                    {% else %}
                    -
                    {% endif %}
                </td>
                <td>
                    {% if item %}
                    {{ item.units }}
                    {% else %}
                    -
                    {% endif %}
                </td>
                
            </tr>
            {% endfor %}
            
        </tbody>

      </table>
{% elif request.GET %}
<p class="my-3">Записей за этот период не найдено.</p>
{% endif%}
    </li>
</ul>
        
{% endblock %}   